name: Validate JSON

on:
    push:

permissions:
    contents: read

jobs:
    validate-json:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: json-yaml-validate
          uses: GrantBirki/json-yaml-validate@v2.6.1
          with:
            files: software.json
            json_schema: schemas/software.json
